- name: Copying MongoDB repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Installing mondodb shell 
  ansible.builtin.command: dnf install -y mongodb-mongosh

- name: Get the {{component}} count
  ansible.builtin.command:  mongosh --host mongodb.devopsprocloud.in --quiet --eval 'db =db.getSiblingDB("catalogue");db.products.estimatedDocumentCount()'
  register: catalogue_count 
  when:  component == "catalogue"

- name: Print the Catalogue Count output 
  ansible.builtin.debug:
    msg: "Output is {{catalogue_count}}"

- name: "Loading {{component}} data into Mongodb"
  ansible.builtin.shell: "mongosh --host mongodb.devopsprocloud.in </app/schema/{{component}}.js"
  when: 
    - catalogue_count.stdout == "0"
    - component == "catalogue"
  #when: output.stdout != "0"

- name: get the {{component}} count
  ansible.builtin.command:  mongosh --host mongodb.devopsprocloud.in --quiet --eval 'db =db.getSiblingDB("users");db.users.estimatedDocumentCount()'
  register: user_count
  when: component == "user"
  
- name: Print the User Count output 
  ansible.builtin.debug:
    msg: "Output is {{user_count}}"

- name: "Loading {{component}} data into Mongodb" 
  ansible.builtin.shell: mongosh --host mongodb.devopsprocloud.in </app/schema/{{component}}.js
  when: 
    - user_count.stdout == "0"
    - component == "user"
  # when: output.stdout != "0"


